sudo: false
language: python
python:
- '2.7'
- '3.6'
install:
- pip install pipenv --quiet
- pipenv lock
- make
- pip install --quiet codecov
script:
- make test
after_success:
- codecov
deploy:
  provider: pypi
  user: ohara.andrew314
  password:
    secure: CHgADToTbQhNXn6qCfpW8sK9URIV/1njlXLUSVEEb4q1Zc/nL5CoUO8482/28ma54jZdUlqR2Sg7pH+yuRXVV/eBnXL7z1vnD+urTuFG2Q+q/xOpP9ze8dOaoNxHn3iZJM+6GPaVrNLlFqKt8fBjtBeUJeRagAzrarYfe6LSUmic4+keLQG0ccjsBczgRlfY/v3wxOHte5vIiPCgIom7y8YmthCEpV9hu36GIYigIi69vm6DlgNhGrh2Ph36tbA6lqVeSQQp2iX5p7HjzgGvH17YxiuIjZlGGg/uhkaIaLfk0+iBP3vHsawnlc4RCfAI/s2E5Rbu3QDUw/hbmFAVuoIHC6Yxw/Tk3uCfyOF8FziBw7HjQTgYXPU5Vb9U7rJzmRhF6XIbXQzn5/Zx1QrgvoEDN0I5Vew7CbUWUxMdeVqF07Q0zRkuI5seo62UslzbbqpzpmqKNEOFFdEkps49O7JRRxMkiTiNxweQjZElPptJRWWnRWA5ExjAfPSwNptKasD96WDNdpPPJeJyzWy9zi3LDRC4OGzwO78Uv5eMPNKc7d97YjkxV3JweBPopMmqysAHNNmqEnreB2fbCPGgILIBFeD2UglI1HqkAFyAizRdx57jU2wxlkEMM8hnaAVYiYczsFwLWCGykIpnJI7vqNbn71EBJAVhylviPE96FXU=
cache: pip
